/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

/**
 *
 * @author RafaelMR
 */
public class cadastro extends javax.swing.JFrame {

    /**
     * Creates new form cadastro
     */
    public cadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nomeEmpresa = new javax.swing.JLabel();
        nomeArea = new javax.swing.JLabel();
        textoNome = new javax.swing.JLabel();
        textoCPF = new javax.swing.JLabel();
        textoNascimento = new javax.swing.JLabel();
        textoTelefone = new javax.swing.JLabel();
        TextoEmail = new javax.swing.JLabel();
        textoSenha = new javax.swing.JLabel();
        textoConfSenha = new javax.swing.JLabel();
        entradaNome = new javax.swing.JTextField();
        entradaCPF = new javax.swing.JTextField();
        entradaNascimento = new javax.swing.JTextField();
        entradaTelefone = new javax.swing.JTextField();
        entradaEmail = new javax.swing.JTextField();
        entradaSenha = new javax.swing.JPasswordField();
        entradaConfSenha = new javax.swing.JPasswordField();
        botaoCadastro = new java.awt.Button();
        botaoLogin = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        nomeEmpresa.setFont(new java.awt.Font("Arial Black", 0, 48)); // NOI18N
        nomeEmpresa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nomeEmpresa.setText("ACM Contábil");

        nomeArea.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        nomeArea.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nomeArea.setText("Área de cadastro");

        textoNome.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        textoNome.setText("Nome completo:");

        textoCPF.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        textoCPF.setText("CPF:");

        textoNascimento.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        textoNascimento.setText("Data de nascimento:");

        textoTelefone.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        textoTelefone.setText("Telefone:");

        TextoEmail.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        TextoEmail.setText("Email:");

        textoSenha.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        textoSenha.setText("Senha:");

        textoConfSenha.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        textoConfSenha.setText("Confirmar senha:");

        entradaNome.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        entradaNome.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        entradaNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entradaNomeActionPerformed(evt);
            }
        });

        entradaCPF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        entradaCPF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        entradaCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entradaCPFActionPerformed(evt);
            }
        });

        entradaNascimento.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        entradaNascimento.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        entradaNascimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entradaNascimentoActionPerformed(evt);
            }
        });

        entradaTelefone.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        entradaTelefone.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        entradaTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entradaTelefoneActionPerformed(evt);
            }
        });

        entradaEmail.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        entradaEmail.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        entradaEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entradaEmailActionPerformed(evt);
            }
        });

        entradaSenha.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        entradaSenha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        entradaSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entradaSenhaActionPerformed(evt);
            }
        });

        entradaConfSenha.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        entradaConfSenha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        entradaConfSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entradaConfSenhaActionPerformed(evt);
            }
        });

        botaoCadastro.setActionCommand("button");
        botaoCadastro.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        botaoCadastro.setLabel("CADASTRAR");
        botaoCadastro.setName(""); // NOI18N
        botaoCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastroActionPerformed(evt);
            }
        });

        botaoLogin.setActionCommand("button");
        botaoLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        botaoLogin.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        botaoLogin.setLabel("VOLTAR PARA ÁREA DE LOGIN");
        botaoLogin.setName(""); // NOI18N
        botaoLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(361, 361, 361)
                .addComponent(textoSenha)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(entradaConfSenha)
                    .addComponent(entradaSenha, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(entradaNascimento))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(entradaTelefone)
                        .addContainerGap())
                    .addComponent(nomeEmpresa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(nomeArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(entradaNome, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(entradaCPF, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(entradaEmail))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(304, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(textoNascimento)
                        .addGap(299, 299, 299))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(textoCPF)
                        .addGap(372, 372, 372))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(textoNome)
                        .addGap(314, 314, 314))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(TextoEmail)
                        .addGap(365, 365, 365))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(textoTelefone)
                        .addGap(350, 350, 350))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(textoConfSenha)
                        .addGap(310, 310, 310))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(botaoCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(103, 103, 103)
                        .addComponent(botaoLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nomeEmpresa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(nomeArea)
                .addGap(18, 18, 18)
                .addComponent(textoNome)
                .addGap(2, 2, 2)
                .addComponent(entradaNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textoCPF)
                .addGap(2, 2, 2)
                .addComponent(entradaCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textoNascimento)
                .addGap(5, 5, 5)
                .addComponent(entradaNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(textoTelefone)
                .addGap(2, 2, 2)
                .addComponent(entradaTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(TextoEmail)
                .addGap(2, 2, 2)
                .addComponent(entradaEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textoSenha)
                .addGap(2, 2, 2)
                .addComponent(entradaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textoConfSenha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(entradaConfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botaoCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void entradaNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entradaNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entradaNomeActionPerformed

    private void entradaCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entradaCPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entradaCPFActionPerformed

    private void entradaNascimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entradaNascimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entradaNascimentoActionPerformed

    private void entradaTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entradaTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entradaTelefoneActionPerformed

    private void entradaEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entradaEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entradaEmailActionPerformed

    private void entradaSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entradaSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entradaSenhaActionPerformed

    private void entradaConfSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entradaConfSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entradaConfSenhaActionPerformed

    private void botaoCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoCadastroActionPerformed

    private void botaoLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TextoEmail;
    private java.awt.Button botaoCadastro;
    private java.awt.Button botaoLogin;
    private javax.swing.JTextField entradaCPF;
    private javax.swing.JPasswordField entradaConfSenha;
    private javax.swing.JTextField entradaEmail;
    private javax.swing.JTextField entradaNascimento;
    private javax.swing.JTextField entradaNome;
    private javax.swing.JPasswordField entradaSenha;
    private javax.swing.JTextField entradaTelefone;
    private javax.swing.JLabel nomeArea;
    private javax.swing.JLabel nomeEmpresa;
    private javax.swing.JLabel textoCPF;
    private javax.swing.JLabel textoConfSenha;
    private javax.swing.JLabel textoNascimento;
    private javax.swing.JLabel textoNome;
    private javax.swing.JLabel textoSenha;
    private javax.swing.JLabel textoTelefone;
    // End of variables declaration//GEN-END:variables
}
