/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

/**
 *
 * @author RafaelMR
 */
public class envioDocumento extends javax.swing.JFrame {

    /**
     * Creates new form envioDocumento
     */
    public envioDocumento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jSeparator1 = new javax.swing.JSeparator();
        nomeEmpresa = new javax.swing.JLabel();
        nomeArea = new javax.swing.JLabel();
        textoDadosPessoais = new javax.swing.JLabel();
        textoDependentes = new javax.swing.JLabel();
        textoRendimentos = new javax.swing.JLabel();
        textoBensDireitos = new javax.swing.JLabel();
        textoDividasOnus = new javax.swing.JLabel();
        textoDoacao = new javax.swing.JLabel();
        textoInvestimento = new javax.swing.JLabel();
        textoLinkDrive1 = new javax.swing.JLabel();
        textoLinkDrive2 = new javax.swing.JLabel();
        textoLinkDrive3 = new javax.swing.JLabel();
        textoLinkDrive4 = new javax.swing.JLabel();
        textoLinkDrive5 = new javax.swing.JLabel();
        textoLinkDrive6 = new javax.swing.JLabel();
        textoLinkDrive7 = new javax.swing.JLabel();
        botaoModeloDados = new javax.swing.JButton();
        botaoModeloDependente = new javax.swing.JButton();
        botaoModeloRendimento = new javax.swing.JButton();
        botaoModeloBens = new javax.swing.JButton();
        botaoModeloDividas = new javax.swing.JButton();
        botaoModeloDoacao = new javax.swing.JButton();
        botaoModeloInvestimento = new javax.swing.JButton();
        botaoEnviarDados = new javax.swing.JButton();
        botaoEnviarDependentes = new javax.swing.JButton();
        botaoEnviarRendimentos = new javax.swing.JButton();
        botaoEnviarBens = new javax.swing.JButton();
        botaoEnviarDividas = new javax.swing.JButton();
        botaoEnviarDoacao = new javax.swing.JButton();
        botaoEnviarInvestimentos = new javax.swing.JButton();
        botaoDesconectar = new java.awt.Button();
        entradaLinkDados = new javax.swing.JTextField();
        entradaLinkDependentes = new javax.swing.JTextField();
        entradaLinkRendimentos = new javax.swing.JTextField();
        entradaLinkBens = new javax.swing.JTextField();
        entradaLinkDividas = new javax.swing.JTextField();
        entradaLinkDoacao = new javax.swing.JTextField();
        entradaLinkInvestimentos = new javax.swing.JTextField();
        linha01 = new javax.swing.JSeparator();
        linha02 = new javax.swing.JSeparator();
        linha03 = new javax.swing.JSeparator();
        linha04 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nomeEmpresa.setFont(new java.awt.Font("Arial Black", 0, 48)); // NOI18N
        nomeEmpresa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nomeEmpresa.setText("ACM Contábil");

        nomeArea.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        nomeArea.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nomeArea.setText("Envio de documentos");

        textoDadosPessoais.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        textoDadosPessoais.setText("DADOS PESSOAIS");

        textoDependentes.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        textoDependentes.setText("DEPENDENTES");

        textoRendimentos.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        textoRendimentos.setText("RENDIMENTOS");

        textoBensDireitos.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        textoBensDireitos.setText("BENS E DIREITOS");

        textoDividasOnus.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        textoDividasOnus.setText("DÍVIDAS E ÔNUS");

        textoDoacao.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        textoDoacao.setText("DOAÇÕES EFETUADAS");

        textoInvestimento.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        textoInvestimento.setText("Investimentos");

        textoLinkDrive1.setText("Coloque o link do documento no Google Drive:");

        textoLinkDrive2.setText("Coloque o link do documento no Google Drive:");

        textoLinkDrive3.setText("Coloque o link do documento no Google Drive:");

        textoLinkDrive4.setText("Coloque o link do documento no Google Drive:");

        textoLinkDrive5.setText("Coloque o link do documento no Google Drive:");

        textoLinkDrive6.setText("Coloque o link do documento no Google Drive:");

        textoLinkDrive7.setText("Coloque o link do documento no Google Drive:");

        botaoModeloDados.setText("Modelo de tabela");

        botaoModeloDependente.setText("Modelo de tabela");

        botaoModeloRendimento.setText("Modelo de tabela");

        botaoModeloBens.setText("Modelo de tabela");

        botaoModeloDividas.setText("Modelo de tabela");

        botaoModeloDoacao.setText("Modelo de tabela");

        botaoModeloInvestimento.setText("Modelo de tabela");

        botaoEnviarDados.setText("Enviar dados Pessoais");

        botaoEnviarDependentes.setText("Enviar dependentes");

        botaoEnviarRendimentos.setText("Enviar rendimentos");

        botaoEnviarBens.setText("Enviar bens e direitos");

        botaoEnviarDividas.setText("Enviar dívidas e ônus");

        botaoEnviarDoacao.setText("Enviar doações efetuadas");

        botaoEnviarInvestimentos.setText("Enviar investimentos");

        botaoDesconectar.setActionCommand("button");
        botaoDesconectar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        botaoDesconectar.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        botaoDesconectar.setLabel("VOLTAR PARA O MENU");
        botaoDesconectar.setName(""); // NOI18N
        botaoDesconectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoDesconectarActionPerformed(evt);
            }
        });

        entradaLinkDados.setToolTipText("");
        entradaLinkDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entradaLinkDadosActionPerformed(evt);
            }
        });

        entradaLinkDependentes.setToolTipText("");
        entradaLinkDependentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entradaLinkDependentesActionPerformed(evt);
            }
        });

        entradaLinkRendimentos.setToolTipText("");

        entradaLinkBens.setToolTipText("");

        entradaLinkDividas.setToolTipText("");

        entradaLinkDoacao.setToolTipText("");

        entradaLinkInvestimentos.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nomeEmpresa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(nomeArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(entradaLinkDados, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(116, 116, 116)
                                .addComponent(textoDadosPessoais))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(textoLinkDrive1)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 366, Short.MAX_VALUE)
                                .addComponent(botaoDesconectar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(74, 74, 74)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(57, 57, 57)
                                        .addComponent(botaoModeloDependente)
                                        .addGap(18, 18, 18)
                                        .addComponent(botaoEnviarDependentes))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(entradaLinkDependentes, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(textoDependentes)
                                .addGap(172, 172, 172))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(textoLinkDrive2)
                                .addGap(103, 103, 103))))))
            .addComponent(linha01)
            .addComponent(linha02, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(botaoModeloDados)
                .addGap(18, 18, 18)
                .addComponent(botaoEnviarDados)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addComponent(textoRendimentos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(textoBensDireitos)
                .addGap(159, 159, 159))
            .addGroup(layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(textoLinkDrive3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(textoLinkDrive4)
                .addGap(94, 94, 94))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(textoDividasOnus))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(entradaLinkDividas, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(botaoModeloDividas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botaoEnviarDividas))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botaoModeloRendimento)
                            .addComponent(textoLinkDrive5))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(textoDoacao))
                    .addComponent(entradaLinkDoacao, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(textoLinkDrive6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(botaoModeloDoacao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoEnviarDoacao)))
                .addGap(46, 46, 46))
            .addComponent(linha04, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(231, 231, 231)
                .addComponent(botaoEnviarRendimentos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botaoModeloBens)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botaoEnviarBens)
                .addGap(82, 82, 82))
            .addComponent(linha03, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(entradaLinkRendimentos, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(81, 81, 81)
                        .addComponent(entradaLinkBens, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(326, 326, 326)
                        .addComponent(textoLinkDrive7))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(265, 265, 265)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(entradaLinkInvestimentos, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(botaoModeloInvestimento)
                                .addGap(28, 28, 28)
                                .addComponent(botaoEnviarInvestimentos))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(402, 402, 402)
                        .addComponent(textoInvestimento)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(nomeEmpresa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nomeArea)
                .addGap(21, 21, 21)
                .addComponent(linha01, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(textoDadosPessoais)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textoLinkDrive1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(entradaLinkDados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botaoModeloDados)
                            .addComponent(botaoEnviarDados)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(textoDependentes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textoLinkDrive2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(entradaLinkDependentes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botaoEnviarDependentes)
                            .addComponent(botaoModeloDependente))))
                .addGap(19, 19, 19)
                .addComponent(linha02, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoBensDireitos)
                    .addComponent(textoRendimentos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoLinkDrive3)
                    .addComponent(textoLinkDrive4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(entradaLinkBens, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(entradaLinkRendimentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoEnviarBens)
                    .addComponent(botaoModeloBens)
                    .addComponent(botaoEnviarRendimentos)
                    .addComponent(botaoModeloRendimento))
                .addGap(24, 24, 24)
                .addComponent(linha03, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(textoDividasOnus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textoLinkDrive5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(entradaLinkDividas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botaoModeloDividas)
                            .addComponent(botaoEnviarDividas)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(textoDoacao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textoLinkDrive6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(entradaLinkDoacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botaoModeloDoacao)
                            .addComponent(botaoEnviarDoacao))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(linha04, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textoInvestimento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textoLinkDrive7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(entradaLinkInvestimentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botaoDesconectar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(botaoModeloInvestimento)
                        .addComponent(botaoEnviarInvestimentos)))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        botaoDesconectar.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoDesconectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoDesconectarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoDesconectarActionPerformed

    private void entradaLinkDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entradaLinkDadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entradaLinkDadosActionPerformed

    private void entradaLinkDependentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entradaLinkDependentesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entradaLinkDependentesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(envioDocumento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(envioDocumento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(envioDocumento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(envioDocumento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new envioDocumento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button botaoDesconectar;
    private javax.swing.JButton botaoEnviarBens;
    private javax.swing.JButton botaoEnviarDados;
    private javax.swing.JButton botaoEnviarDependentes;
    private javax.swing.JButton botaoEnviarDividas;
    private javax.swing.JButton botaoEnviarDoacao;
    private javax.swing.JButton botaoEnviarInvestimentos;
    private javax.swing.JButton botaoEnviarRendimentos;
    private javax.swing.JButton botaoModeloBens;
    private javax.swing.JButton botaoModeloDados;
    private javax.swing.JButton botaoModeloDependente;
    private javax.swing.JButton botaoModeloDividas;
    private javax.swing.JButton botaoModeloDoacao;
    private javax.swing.JButton botaoModeloInvestimento;
    private javax.swing.JButton botaoModeloRendimento;
    private javax.swing.JTextField entradaLinkBens;
    private javax.swing.JTextField entradaLinkDados;
    private javax.swing.JTextField entradaLinkDependentes;
    private javax.swing.JTextField entradaLinkDividas;
    private javax.swing.JTextField entradaLinkDoacao;
    private javax.swing.JTextField entradaLinkInvestimentos;
    private javax.swing.JTextField entradaLinkRendimentos;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator linha01;
    private javax.swing.JSeparator linha02;
    private javax.swing.JSeparator linha03;
    private javax.swing.JSeparator linha04;
    private javax.swing.JLabel nomeArea;
    private javax.swing.JLabel nomeEmpresa;
    private javax.swing.JLabel textoBensDireitos;
    private javax.swing.JLabel textoDadosPessoais;
    private javax.swing.JLabel textoDependentes;
    private javax.swing.JLabel textoDividasOnus;
    private javax.swing.JLabel textoDoacao;
    private javax.swing.JLabel textoInvestimento;
    private javax.swing.JLabel textoLinkDrive1;
    private javax.swing.JLabel textoLinkDrive2;
    private javax.swing.JLabel textoLinkDrive3;
    private javax.swing.JLabel textoLinkDrive4;
    private javax.swing.JLabel textoLinkDrive5;
    private javax.swing.JLabel textoLinkDrive6;
    private javax.swing.JLabel textoLinkDrive7;
    private javax.swing.JLabel textoRendimentos;
    // End of variables declaration//GEN-END:variables
}
