/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

/**
 *
 * @author RafaelMR
 */
public class recSenha extends javax.swing.JFrame {

    /**
     * Creates new form recSenha
     */
    public recSenha() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nomeEmpresa = new javax.swing.JLabel();
        nomeArea = new javax.swing.JLabel();
        textoEmail = new javax.swing.JLabel();
        textoCodigo = new javax.swing.JLabel();
        textoSenha = new javax.swing.JLabel();
        textoConfSenha = new javax.swing.JLabel();
        entradaEmail = new javax.swing.JTextField();
        entradaCodigo = new javax.swing.JTextField();
        entradaSenha = new javax.swing.JPasswordField();
        entradaConfSenha = new javax.swing.JPasswordField();
        botaoCodigo = new java.awt.Button();
        botaoMudSenha = new java.awt.Button();
        botaoLogin = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nomeEmpresa.setFont(new java.awt.Font("Arial Black", 0, 48)); // NOI18N
        nomeEmpresa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nomeEmpresa.setText("ACM Contábil");

        nomeArea.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        nomeArea.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nomeArea.setText("Área de recuperação de senha");

        textoEmail.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        textoEmail.setText("Digite seu email:");

        textoCodigo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        textoCodigo.setText("Informe o código recebido:");

        textoSenha.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        textoSenha.setText("Informe a nova senha:");

        textoConfSenha.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        textoConfSenha.setText("Confirme a nova senha:");

        entradaEmail.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        entradaEmail.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        entradaEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entradaEmailActionPerformed(evt);
            }
        });

        entradaCodigo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        entradaCodigo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        entradaCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entradaCodigoActionPerformed(evt);
            }
        });

        entradaSenha.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        entradaSenha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        entradaSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entradaSenhaActionPerformed(evt);
            }
        });

        entradaConfSenha.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        entradaConfSenha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        entradaConfSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entradaConfSenhaActionPerformed(evt);
            }
        });

        botaoCodigo.setActionCommand("button");
        botaoCodigo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        botaoCodigo.setLabel("RECEBER CÓDIGO");
        botaoCodigo.setName(""); // NOI18N
        botaoCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCodigoActionPerformed(evt);
            }
        });

        botaoMudSenha.setActionCommand("button");
        botaoMudSenha.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        botaoMudSenha.setLabel("ALTERAR SENHA");
        botaoMudSenha.setName(""); // NOI18N
        botaoMudSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoMudSenhaActionPerformed(evt);
            }
        });

        botaoLogin.setActionCommand("button");
        botaoLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        botaoLogin.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        botaoLogin.setLabel("VOLTAR PARA ÁREA DE LOGIN");
        botaoLogin.setName(""); // NOI18N
        botaoLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(botaoMudSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(308, 308, 308))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(textoSenha)
                        .addGap(288, 288, 288))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(textoCodigo)
                        .addGap(273, 273, 273))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(302, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(textoConfSenha)
                        .addGap(285, 285, 285))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(botaoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(299, 299, 299))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(entradaConfSenha)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(botaoLogin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(textoEmail)
                                        .addGap(305, 305, 305))))
                            .addComponent(nomeEmpresa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nomeArea, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 778, Short.MAX_VALUE)
                            .addComponent(entradaEmail, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(entradaCodigo)))
                    .addComponent(entradaSenha, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nomeEmpresa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nomeArea)
                .addGap(69, 69, 69)
                .addComponent(textoEmail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(entradaEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(textoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(entradaCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textoSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(entradaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textoConfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(entradaConfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoMudSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void entradaEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entradaEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entradaEmailActionPerformed

    private void entradaCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entradaCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entradaCodigoActionPerformed

    private void botaoCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoCodigoActionPerformed

    private void botaoLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoLoginActionPerformed

    private void botaoMudSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoMudSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoMudSenhaActionPerformed

    private void entradaConfSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entradaConfSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entradaConfSenhaActionPerformed

    private void entradaSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entradaSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entradaSenhaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(recSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(recSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(recSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(recSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new recSenha().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button botaoCodigo;
    private java.awt.Button botaoLogin;
    private java.awt.Button botaoMudSenha;
    private javax.swing.JTextField entradaCodigo;
    private javax.swing.JPasswordField entradaConfSenha;
    private javax.swing.JTextField entradaEmail;
    private javax.swing.JPasswordField entradaSenha;
    private javax.swing.JLabel nomeArea;
    private javax.swing.JLabel nomeEmpresa;
    private javax.swing.JLabel textoCodigo;
    private javax.swing.JLabel textoConfSenha;
    private javax.swing.JLabel textoEmail;
    private javax.swing.JLabel textoSenha;
    // End of variables declaration//GEN-END:variables
}
